
import type { Doctor, Translations } from './types';

export const mockDoctors: Doctor[] = [
    { id: 1, name: "Ama Poku", specialty: "Senior Nephrologist", experience: "15 years", availability: "Mon, Wed, Fri", fee: "GHS 250", image: "https://picsum.photos/seed/drapoku/100/100" },
    { id: 2, name: "Bello Mohammed", specialty: "Consultant Nephrologist", experience: "12 years", availability: "Tue, Thu", fee: "GHS 200", image: "https://picsum.photos/seed/drbello/100/100" },
    { id: 3, name: "Kwame Osei", specialty: "Pediatric Nephrologist", experience: "10 years", availability: "Mon - Fri", fee: "GHS 180", image: "https://picsum.photos/seed/drosei/100/100" }
];

export const translations: Translations = {
  en: {
    appName: "Renal Care",
    welcome: "Welcome to Renal Care",
    welcomeSubtitle: "Your partner in proactive kidney health. Scan a test strip or food item to begin.",
    scanStrip: "Scan Test Strip",
    scanFood: "Scan Food Item",
    home: "Home",
    vitals: "Vitals",
    consult: "Consult",
    wellness: "Wellness",
    games: "Games",
    profile: "Profile",
    testHistory: "Test History",
    noHistory: "No tests recorded yet. Start by scanning a strip.",
    scanInstruction: "Align the test strip within the frame.",
    scanFoodInstruction: "Center the food item or barcode.",
    analyzing: "Analyzing...",
    analyzingFood: "Analyzing Food...",
    scan: "Scan",
    cancel: "Cancel",
    results: "Results",
    healthStatus: "Health Status",
    recommendation: "Recommendation",
    consultDoctor: "Consult a Doctor",
    findClinic: "Find a Nearby Clinic",
    done: "Done",
    backToHome: "Back to Home",
    language: "Language",
    settings: "Settings",
    healthTips: "Kidney Health Tips",
    tip1Title: "Stay Hydrated",
    tip1: "Drink plenty of water throughout the day to help your kidneys function properly.",
    tip2Title: "Eat a Balanced Diet",
    tip2: "Reduce salt, processed foods, and sugar. Focus on fresh fruits, vegetables, and whole grains.",
    tip3Title: "Monitor Blood Pressure",
    tip3: "High blood pressure is a leading cause of kidney damage. Check it regularly.",
    tip4Title: "Be Active",
    tip4: "Regular physical activity helps control blood pressure and weight.",
    biomarkers: "Biomarkers",
    protein: "Protein",
    albumin: "Albumin",
    ph: "pH",
    nitrite: "Nitrite",
    blood: "Blood",
    normal: "Normal",
    trace: "Trace",
    moderate: "Moderate",
    high: "High",
    negative: "Negative",
    positive: "Positive",
    statusNormal: "Normal",
    statusMild: "Mild Risk",
    statusHigh: "High Risk",
    recNormal: "Your kidney function appears to be normal. Keep up the healthy habits!",
    recMild: "A mild risk has been detected. We recommend monitoring your health and consulting a doctor for a follow-up.",
    recHigh: "A high risk has been detected. Please consult a healthcare professional immediately for further evaluation.",
    gameCenter: "Game Center",
    gameCenterSubtitle: "Learn about kidney health in a fun and interactive way!",
    foodSortGameTitle: "Healthy Food Sort",
    foodSortGameDesc: "Sort foods into 'Good for Kidneys' and 'Limit/Avoid' categories.",
    kidneyRunnerGameTitle: "Kidney Runner",
    kidneyRunnerGameDesc: "Keep your kidneys running strong! Catch the good, avoid the bad.",
    hydrationHeroGameTitle: "Hydration Hero",
    hydrationHeroGameDesc: "Tap the water drops to flush out toxins and keep your kidneys clean!",
    playNow: "Play Now",
    goodForKidneys: "Good for Kidneys",
    limitAvoid: "Limit / Avoid",
    score: "Score",
    finalScore: "Final Score",
    playAgain: "Play Again",
    correct: "Correct!",
    incorrect: "Not quite!",
    getAiInsights: "Get AI-Powered Insights",
    aiInsights: "AI-Powered Insights",
    generating: "Generating...",
    mealPlanner: "AI Meal Planner",
    mealPlannerDesc: "Get a personalized, kidney-friendly one-day meal plan.",
    preferences: "Any preferences? (e.g., vegetarian, likes chicken)",
    generatePlan: "Generate Plan",
    breakfast: "Breakfast",
    lunch: "Lunch",
    dinner: "Dinner",
    mealPlanDisclaimer: "This is a sample plan. Consult a nutritionist for a full dietary plan.",
    health: "Health",
    gameOver: "Game Over",
    kidneyFailure: "Kidney Failure!",
    level: "Level",
    levelComplete: "Level Complete!",
    nextLevel: "Next Level",
    kidneyFact: "Kidney Fact",
    fact1: "Did you know your kidneys filter about 150 liters of blood every day?",
    fact2: "Drinking enough water helps your kidneys remove waste from your blood.",
    fact3: "High blood pressure and diabetes are the main causes of kidney disease.",
    startGame: "Start Game",
    findSpecialist: "Find a Specialist",
    findSpecialistDesc: "Book a virtual consultation with a top nephrologist.",
    availableNephrologists: "Available Nephrologists",
    bookAppointment: "Book Appointment",
    dr: "Dr.",
    experience: "Experience",
    availability: "Availability",
    fee: "Fee",
    bookNow: "Book Now",
    selectDateTime: "Select Date & Time",
    confirmBooking: "Confirm Booking",
    appointmentConfirmed: "Appointment Confirmed!",
    appointmentDetails: "Your appointment with Dr. {doctorName} is confirmed for {date} at {time}.",
    backToConsult: "Back to Consultations",
    hydrationTracker: "Hydration Tracker",
    dailyGoal: "Daily Goal",
    todaysIntake: "Today's Intake",
    logWater: "Log Water",
    addGlass: "+1 Glass (250ml)",
    addBottle: "+1 Bottle (500ml)",
    waterLogged: "Water logged!",
    login: "Login",
    signUp: "Sign Up",
    continueAsGuest: "Continue as Guest",
    email: "Email",
    password: "Password",
    name: "Full Name",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    other: "Other",
    preExistingConditions: "Pre-existing Conditions (Optional)",
    hypertension: "Hypertension",
    diabetes: "Diabetes",
    alreadyHaveAccount: "Already have an account?",
    dontHaveAccount: "Don't have an account?",
    signOut: "Sign Out",
    trackVitals: "Track Your Vitals",
    trackVitalsDesc: "Regularly logging your vitals helps create a clearer picture of your health.",
    bloodPressure: "Blood Pressure",
    systolic: "Systolic (mmHg)",
    diastolic: "Diastolic (mmHg)",
    bloodGlucose: "Blood Glucose",
    glucoseLevel: "Level (mg/dL)",
    bodyMassIndex: "Body Mass Index (BMI)",
    weight: "Weight (kg)",
    height: "Height (cm)",
    saveVitals: "Save Vitals",
    latestVitals: "Latest Vitals",
    noVitals: "No vitals recorded yet.",
    lastRecorded: "Last recorded on",
    highBP: "High BP — kidney strain risk",
    highGlucose: "High glucose — diabetic kidney risk",
    overweight: "Overweight — maintain hydration",
    normalVitals: "Vitals are within normal range.",
    myProfile: "My Profile",
    hydration: "Hydration",
    mealPlan: "Meal Plan",
    toxinLevel: "Toxin Level",
    kidneysOverwhelmed: "Kidneys Overwhelmed!",
    getAiHealthReport: "Get My AI Health Report",
    getAiVitalsAnalysis: "Get AI Vitals Analysis",
    aiHealthReport: "AI Health Report",
    generatingReport: "Generating your personalized health report...",
    notEnoughData: "Not enough data for a report. Please log a test and your vitals first.",
    notEnoughDataError: "Not enough data for a report. Please log your {missingData} first.",
    foodScanner: "AI Food Scanner",
    foodScanResult: "Food Scan Result",
    kidneyImpactScore: "Kidney Impact Score",
    nutritionalInfo: "Nutritional Info (Estimated)",
    sodium: "Sodium",
    potassium: "Potassium",
    phosphorus: "Phosphorus",
    sugar: "Sugar",
    lowImpact: "Low Impact",
    moderateImpact: "Moderate Impact",
    highImpact: "High Impact",
    alternatives: "Healthier Alternatives",
    consumptionAdvice: "Consumption Advice",
    scanAgain: "Scan Another Item",
    chatWithAI: "Chat with AI Assistant",
    chatWithAIDesc: "Get instant answers to your health questions.",
    bookDoctor: "Book a Doctor",
    bookDoctorDesc: "Connect with a certified nephrologist.",
    aiChatbot: "AI Chatbot",
    askMeAnything: "Ask me anything about kidney health...",
    aiDisclaimer: "I am an AI assistant and not a medical professional. Please consult a doctor for medical advice.",
    listening: "Listening...",
    tapToStop: "Tap mic to stop",
    voiceError: "Voice recognition error. Please try again.",
    voiceErrorNoSpeech: "I didn't hear anything. Please tap the mic and try speaking again.",
    voiceErrorNotAllowed: "I can't access your microphone. Please check your browser permissions.",
    playingAudio: "Playing...",
    playAudio: "Play",
  },
  tw: {
    appName: "Renal Care",
    welcome: "Akwaaba kɔ Renal Care",
    welcomeSubtitle: "Wo hokafoɔ wɔ asaabo akwahosan mu. Fa test strip no scan anaa aduane bi na hyɛ aseɛ.",
    scanStrip: "Scan Test Strip",
    scanFood: "Scan Aduane",
    home: "Fie",
    vitals: "Vitals",
    consult: "Consult",
    wellness: "Akwahosan",
    games: "Agorɔ",
    profile: "Profile",
    testHistory: "Test Abakɔsɛm",
    noHistory: "Test biara nni hɔ. Hyɛ aseɛ denam strip a wobɛ scan so.",
    scanInstruction: "Fa test strip no hyɛ frame no mu pɛpɛɛpɛ.",
    scanFoodInstruction: "Fa aduane anaa barcode no to mfimfini.",
    analyzing: "Ɛreyɛ mu...",
    analyzingFood: "Ɛreyɛ Aduane Mu...",
    scan: "Scan",
    cancel: "Gyae",
    results: "Nsunsuansoɔ",
    healthStatus: "Akwahosan Tebea",
    recommendation: "Afutuo",
    consultDoctor: "Kɔsrɛ Dɔkota",
    findClinic: "Hwehwɛ Ayaresabea a ɛbɛn",
    done: "Yɛawie",
    backToHome: "San kɔ Fie",
    language: "Kasa",
    settings: "Nsiesieɛ",
    healthTips: "Asaabo Akwahosan Afutuo",
    tip1Title: "Nom Nsuo Paa",
    tip1: "Nom nsuo bebree da biara na ɛboa wo asaabo ma ɛyɛ adwuma yie.",
    tip2Title: "Di Aduane Pa",
    tip2: "Tete nkyene, aduane a wɔayɛ dedaw, ne asikyire so. Di nnuaba foforɔ, nhabannuru, ne aburow a ɛmu di mu.",
    tip3Title: "Hwɛ Wo Mogya Mmereɛ So",
    tip3: "Mogya mmereɛ a ɛkɔ soro no sɛe asaabo. Hwɛ no daa.",
    tip4Title: "Di Agorɔ",
    tip4: "Apɔmutenetene a woyɛ no daa no boa ma wotumi di wo mogya mmereɛ ne wo mu duru so.",
    biomarkers: "Biomarkers",
    protein: "Protein",
    albumin: "Albumin",
    ph: "pH",
    nitrite: "Nitrite",
    blood: "Mogya",
    normal: "Ɛte sɛ nea ɛsɛ",
    trace: "Kakraa",
    moderate: "Mfinimfini",
    high: "Ɛdɔɔso",
    negative: "Ɛnni mu",
    positive: "Ɛwɔ mu",
    statusNormal: "Ɛte sɛ nea ɛsɛ",
    statusMild: "Asiane Kakraa",
    statusHigh: "Asiane Kɛseɛ",
    recNormal: "Wo asaabo adwumayɛ yɛ. Kɔ so di amanneɛ pa no so!",
    recMild: "Yɛahu asiane kakra bi. Yɛtu wo fo sɛ hwɛ w'akwahosan so na kɔsrɛ dɔkota.",
    recHigh: "Yɛahu asiane kɛseɛ. Yɛsrɛ wo, kɔhu oduruyɛfo ntɛm ara.",
    gameCenter: "Agorɔbea",
    gameCenterSubtitle: "Sua asaabo akwahosan ho nsɛm wɔ ɔkwan a ɛyɛ anigye so!",
    foodSortGameTitle: "Aduane Pa Yiyie",
    foodSortGameDesc: "Yiyi aduane mu gu 'Eye ma Asaabo' ne 'Tete So/Kwati' nkyekyɛmu mu.",
    kidneyRunnerGameTitle: "Asaabo Regya",
    kidneyRunnerGameDesc: "Ma w'asaabo ntumi nyɛ adwuma yie! Kyere aduane pa na kwati bɔne.",
    hydrationHeroGameTitle: "Nsuo Nom Ɔkofoɔ",
    hydrationHeroGameDesc: "Mia nsuo no so na yi efi no firi asaabo no mu!",
    playNow: "Di Agorɔ Seesei",
    goodForKidneys: "Eye ma Asaabo",
    limitAvoid: "Tete So / Kwati",
    score: "Skoa",
    finalScore: "Skoa a Etwa Toɔ",
    playAgain: "Di Agorɔ Bio",
    correct: "Ɛyɛ Yoo!",
    incorrect: "Ɛnyɛ pɛpɛɛpɛ!",
    getAiInsights: "Nya AI Mmuaeɛ",
    aiInsights: "AI Mmuaeɛ",
    generating: "Ɛreyɛ...",
    mealPlanner: "AI Aduane Nhyehyɛeɛ",
    mealPlannerDesc: "Nya da koro aduane nhyehyɛeɛ a ɛboa asaabo.",
    preferences: "Wopɛ biribi titiriw? (e.g., menni nam, mepɛ akokɔnam)",
    generatePlan: "Yɛ Nhyehyɛeɛ",
    breakfast: "Anɔpa Aduane",
    lunch: "Awie Aduane",
    dinner: "Anwummerɛ Aduane",
    mealPlanDisclaimer: "Yɛsrɛ wo, kɔhu aduaneyɛ ho ɔbenfoɔ.",
    health: "Akwahosan",
    gameOver: "Agorɔ Awie",
    kidneyFailure: "Asaabo asɛe!",
    level: "Beaeɛ",
    levelComplete: "Woawie Beaeɛ!",
    nextLevel: "Beaeɛ a Edi Hɔ",
    kidneyFact: "Asaabo Ho Nokwasɛm",
    fact1: "Wunim sɛ w'asaabo yiyi mogya lita 150 mu da biara?",
    fact2: "Nsuo a wunom no boa ma w'asaabo yi efi firi wo mogya mu.",
    fact3: "Mogya mmereɛ a ɛkɔ soro ne asikyireyadeɛ na ɛde asaabo yareɛ ba.",
    startGame: "Hyɛ Agorɔ Ase",
    findSpecialist: "Hwehwɛ Oduruyɛfo Titiriw",
    findSpecialistDesc: "Wo ne nephrologist a wagye din ntumi nni nkitaho.",
    availableNephrologists: "Nephrologists a Wɔwɔ Hɔ",
    bookAppointment: "Yɛ Appointment",
    dr: "Dr.",
    experience: "Suahunu",
    availability: "Bere a ɔwɔ hɔ",
    fee: "Sika a wɔgye",
    bookNow: "Yɛ Seesei",
    selectDateTime: "Yi Da ne Bere",
    confirmBooking: "Hyɛ Appointment no mu den",
    appointmentConfirmed: "Yɛahyɛ Appointment no mu den!",
    appointmentDetails: "Wo appointment a wo ne Dr. {doctorName} yɛe no, yɛahyɛ no den ama {date} {time}.",
    backToConsult: "San Kɔ Nsɛmbisa So",
    hydrationTracker: "Nsuo Nom Nhwehwɛmu",
    dailyGoal: "Da Biara Botae",
    todaysIntake: "Nnɛ Nsuo a Woanom",
    logWater: "Kyerɛw Nsuo a Woanom",
    addGlass: "+ Glass 1 (250ml)",
    addBottle: "+ Bɔtɔ 1 (500ml)",
    waterLogged: "Yɛakyerɛw agu hɔ!",
    login: "Wura mu",
    signUp: "Kyerɛw Wo din",
    continueAsGuest: "Kɔ so sɛ ɔhɔhoɔ",
    email: "Email",
    password: "Password",
    name: "Din a Wɔde Frɛ wo",
    age: "Mfeɛ",
    gender: "Mmarima anaa ɔbaa",
    male: "Mmarima",
    female: "Ɔbaa",
    other: "Foforɔ",
    preExistingConditions: "Yareɛ a Wowɔ dedaw (Sɛ Wopɛ a)",
    hypertension: "Mogya mmereɛ",
    diabetes: "Asikyireyadeɛ",
    alreadyHaveAccount: "Wowɔ akɔɔnto dedaw?",
    dontHaveAccount: "Wonnim akɔɔnto?",
    signOut: "Pue",
    myProfile: "Me Profile",
    hydration: "Nsuo Nom",
    mealPlan: "Aduane Nhyehyɛeɛ",
    toxinLevel: "Efi Tɛkrɛma",
    kidneysOverwhelmed: "Asaabo no abrɛ!",
    getAiHealthReport: "Nya Me AI Akwahosan Amanneɛbɔ",
    getAiVitalsAnalysis: "Nya AI Vitals Nhwehwɛmu",
    aiHealthReport: "AI Akwahosan Amanneɛbɔ",
    generatingReport: "Yɛreyɛ w'ankasa akwahosan amanneɛbɔ...",
    notEnoughData: "Nsɛm a ɛwɔ hɔ no nnɔɔso mma amanneɛbɔ. Yɛsrɛ wo, kyerɛw sɔhwɛ ne wo vitals ansa.",
    notEnoughDataError: "Nsɛm a ɛwɔ hɔ no nnɔɔso mma amanneɛbɔ. Yɛsrɛ wo, di kan kyerɛw wo {missingData} ho nsɛm.",
    foodScanner: "AI Aduane Skaner",
    foodScanResult: "Aduane Skan Nsunsuansoɔ",
    kidneyImpactScore: "Asaabo So Nkɛntɛnsoɔ Skoa",
    nutritionalInfo: "Aduane Mu Nsɛm (Bɛyɛ)",
    sodium: "Nkyene",
    potassium: "Potassium",
    phosphorus: "Phosphorus",
    sugar: "Asikyire",
    lowImpact: "Nkɛntɛnsoɔ Sua",
    moderateImpact: "Nkɛntɛnsoɔ Mfinimfini",
    highImpact: "Nkɛntɛnsoɔ Kɛseɛ",
    alternatives: "Aduane Foforɔ a Eye",
    consumptionAdvice: "Aduane Di Ho Afutuo",
    scanAgain: "Scan Aduane Foforɔ",
    chatWithAI: "Chat ne AI Mmoafoɔ",
    chatWithAIDesc: "Nya mmuaeɛ ntɛm ara fa w'akwahosan nsɛm ho.",
    bookDoctor: "Kɔsrɛ Dɔkota",
    bookDoctorDesc: "Di nkitaho ne oduruyɛfoɔ ankasa.",
aiChatbot: "AI Chatbot",
    askMeAnything: "Bisa me biribiara fa asaabo akwahosan ho...",
    aiDisclaimer: "Meyɛ AI mmoafoɔ na menni oduruyɛfoɔ tumi. Yɛsrɛ wo, kɔsrɛ dɔkota fa aduruyɛ ho afutuo.",
    listening: "Mereyɛ atie...",
    tapToStop: "Mia so na gyae",
    voiceError: "Nne nsiesieɛ mfomsoɔ. Yɛsrɛ wo, bɔ mmɔden bio.",
    voiceErrorNoSpeech: "Mante hwee. Yɛsrɛ wo, mia mic no na bɔ mmɔden kasa bio.",
    voiceErrorNotAllowed: "Mentumi nnya wo microphone no. Yɛsrɛ wo, hwɛ wo browser tumi nsiesieɛ.",
    playingAudio: "Ɛrebɔ...",
    playAudio: "Bɔ",
  },
};
